### ISSUE TITLE
No differentiation between bright/non-bright

### ISSUE THREAD

**Issue by jspv** [wuqs-net/base16-windows-terminal#1]
Noticed in base16-solarized-dark, no differentiation between most colors:  red, green, blue, cyan, etc. Same with other color templates.  Note: the [original template](https://github.com/arzg/base16-solarized-scheme/blob/master/solarized-dark.yaml) shows different colors:

{
    "name": "base16-solarized-dark",
    "background": "#002b36",
    "selectionBackground": "#586e75",
    "black": "#002b36",
    "blue": "#268bd2",
    "brightBlack": "#657b83",
    "brightBlue": "#268bd2",
    "brightCyan": "#2aa198",
    "brightGreen": "#859900",
    "brightPurple": "#6c71c4",
    "brightRed": "#dc322f",
    "brightWhite": "#fdf6e3",
    "brightYellow": "#b58900",
    "cyan": "#2aa198",
    "foreground": "#93a1a1",
    "green": "#859900",
    "purple": "#6c71c4",
    "red": "#dc322f",
    "white": "#93a1a1",
    "yellow": "#b58900"
}

**Comment by wuqs-net** [comment]
This is built based on the base16 guidelines, in which I believe there are in total only 16 colors, and thus no differentiation between the bright and non-bright colors. Also, notice that in the original template `base09` to `base0F` are all completely different colors. So there aren't really "bright" variants in the original template to build with.

**Comment by jspv** [comment]
Base16 uses 16 colors e.g. https://github.com/aramisgithub/base16-solarized-scheme. These should be mapped the 16 colors necessary to establish the palette of the scheme.  To get a 16 color palette in a 16 color terminal, you need to replace the 'bright' colors with the rest of the palette.  Seee the following examples: [mintty](https://github.com/iamthad/base16-mintty/blob/master/templates/default.mustache), [alacritty](https://github.com/aaron-williamson/base16-alacritty/blob/master/templates/default.mustache), and another [Windows Terminal](https://github.com/ShiromMakkad/base16-windows-terminal/blob/master/templates/default.mustache) which all use identical mappings in their base16 templates for the bright colors.  Happy to send you a PR with an updated template.

**Comment by wuqs-net** [comment]
PRs are always welcome!! Again... I'm still thinking about whether it's right to make this change, since in http://chriskempson.com/projects/base16/, the base01-04 colors are used as background colors. Using those as "bright" colors would probably just make the "bright colors" all grey (in different shade though). Correct me if I'm wrong.

**Comment by jspv** [comment]
Yes, using the bright colors would make them grey or some other color - it depends completely on the color scheme being chosen.  As an example a look at [solarized](https://ethanschoonover.com/solarized/) at the section "The Values" near the bottom - you can see the historical Terminal color names (blue, 'brblue, cyan, brcyan, etc.) but the colors being mapped in the scheme are not those colors.  Those are just the historical names of the 16 color spots in the terminal.

**Comment by damnskippy** [comment]
@jspv @wuqs-net I was puzzled to see many of my terminal colors were grey (when using base16-default-dark) and found this change to be the reason.  I'm not really sure why or when it would make sense to use a grey color in place of red/green/yellow.  The terminal colors seem "right" when the bright and non-bright versions are the same.  After digging through base16 pages some more, it seems there are two variants base16 and 256 version of it.  In the 256 version the bright colors have different colors whereas the default base16 same colors are used for bright and non-bright versions.  Would've expected the 256 colors to be better with more colors but instead having greys in place of colors seems to do the opposite, so not quite clear what the intent is.

**Comment by wuqs-net** [comment]
@damnskippy Sorry for the (extremely) late response, but I've included the 256 version which will work the way you expected. The reason those colors turn grey is that base16 interprets the 16 colors in a different way from the normal ANSI terminal. For the intent you will have to look at [the base16 specification](https://github.com/chriskempson/base16/blob/main/styling.md). And @jspv was following other implementations of base16 which set the colors this way.
